<?php
namespace App\Controller;

use App\Controller\AppController;
use App\Controller\CrawlerController;

/**
 * ListNews Controller
 *
 *
 * @method \App\Model\Entity\ListNews[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ListNewsController extends AppController
{
    protected $content;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->content = new CrawlerController();
    }
    
    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $source = $this->request->getQuery('source');
        $class = 'getContent' . $source;
        $response = $this->content->$class();
        //var_dump($response);
        $this->set(compact('response'));
    }
    
}
