<?php
namespace App\Controller;

use App\Controller\AppController;
use App\Model\Entity\Post;
use Cake\Routing\Router;

/**
 * Post Controller
 *
 *
 * @method \App\Model\Entity\Post[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 * @var \App\Model\Entity\Post
 * @property  \App\Model\Table\PostTable $Post
 * @property  \Cake\View\Helper\UrlHelper $Url
 */
class PostController extends AppController
{
    /**
     *
     */
    public function initialize()
    {
        $this->layout = 'translation';
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    public function add()
    {
        $post = $this->Post->newEntity();
        if ($this->request->is('post')) {
            $post = $this->Post->patchEntity($post, $this->request->getData());
            $post->created = time();
            $post->content = str_replace("\n", "<br/>", $post->content);
            if ($this->Post->save($post)) {
                $id = $post->id;
                $this->redirect(Router::url([
                    'action' => 'view',
                    '?' => [
                        'id' => $id
                    ]
                ]));
            } else {
                $this->redirect(Router::url([
                    'action' => 'add',
                ]));
            }
        }
    }

    public function view()
    {
        $id = $this->request->getQuery('id');
        $post = $this->Post->get($id, [
            'contain' => []
        ]);

        $this->set('post', $post);
    }

}
