<?php
/**
 * Created by PhpStorm.
 * User: TruongNv
 * Date: 2019-06-10
 * Time: 1:39 PM
 */

namespace App\Controller\Component;

use Cake\Controller\Component;
use Cake\Http\Session;
use Google\Cloud\Translate\TranslateClient;

class ComTranslationComponent extends Component
{
    protected $session;

    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
        $this->session = new Session();
    }

    public function convertToHtml($content)
    {
        $content = str_replace(htmlentities('<br>'), "<br>", $content);
        $content = str_replace(htmlentities('<span>'), "<span>", $content);
        $content = str_replace(htmlentities('</span>'), "</span>", $content);
        $content = str_replace(htmlentities('<span class="bg-warning text-selected">'), '<span class="bg-warning text-selected">' , $content);
        $content = str_replace(htmlentities('<span class="">'), '<span class="">' , $content);
        $content = str_replace(htmlentities('<text class="display-text">'), '<text class="display-text">' , $content);
        $content = str_replace(htmlentities('</text>'), '</text>' , $content);
        return $content;
    }
    public function convertToString($content)
    {
        $content = str_replace("&lt;br/&gt;", "&lt;br/&gt;", $content);
        $content = str_replace("&lt;span&gt;", "&lt;span&gt;", $content);
        $content = str_replace("&lt;/span&gt;", "&lt;/span&gt;", $content);
        return $content;
    }

    public function replaceBreakElement($content)
    {
        str_replace("\n", "<span><br></span>", $content);
        return $content;
    }

    public function breakAllString($content)
    {
        $expStr = explode(" ", $content);
        $strAddElm = '';
        foreach ($expStr as $value) {
            $strAddElm .= "<span>" . $value . "</span> ";
        }
        return $strAddElm;
    }

    public function translate($text)
    {
        $translate = new TranslateClient([
            'projectId' => GG_TRAN_PR_ID,
            'key' => GG_API_KEY]);
        $targetLanguage = 'vi';
        $result = $translate->translate($text, [
            'target' => $targetLanguage,
        ]);
        return $result['text'];
    }
}